version: "2"

services:
  redis:
    image: redis:latest
  team_alpha_project:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    links:
      - redis
